export const GENERATE_DAI_REQUEST = 'GENERATE_DAI_REQUEST';
export const GENERATE_DAI_SUCCESS = 'GENERATE_DAI_SUCCESS';
export const GENERATE_DAI_FAILURE = 'GENERATE_DAI_FAILURE';

export const GET_MAX_DAI_REQUEST = 'GET_MAX_DAI_REQUEST';
export const GET_MAX_DAI_SUCCESS = 'GET_MAX_DAI_SUCCESS';
export const GET_MAX_DAI_FAILURE = 'GET_MAX_DAI_FAILURE';

export const WITHDRAW_ETH_REQUEST = 'WITHDRAW_ETH_REQUEST';
export const WITHDRAW_ETH_SUCCESS = 'WITHDRAW_ETH_SUCCESS';
export const WITHDRAW_ETH_FAILURE = 'WITHDRAW_ETH_FAILURE';

export const GET_MAX_ETH_WITHDRAW_REQUEST = 'GET_MAX_ETH_WITHDRAW_REQUEST';
export const GET_MAX_ETH_WITHDRAW_SUCCESS = 'GET_MAX_ETH_WITHDRAW_SUCCESS';
export const GET_MAX_ETH_WITHDRAW_FAILURE = 'GET_MAX_ETH_WITHDRAW_FAILURE';

export const ADD_COLLATERAL_REQUEST = 'ADD_COLLATERAL_REQUEST';
export const ADD_COLLATERAL_SUCCESS = 'ADD_COLLATERAL_SUCCESS';
export const ADD_COLLATERAL_FAILURE = 'ADD_COLLATERAL_FAILURE';
