export const GENERATE_DAI_REQUEST = 'GENERATE_DAI_REQUEST';
export const GENERATE_DAI_SUCCESS = 'GENERATE_DAI_SUCCESS';
export const GENERATE_DAI_FAILURE = 'GENERATE_DAI_FAILURE';

export const GET_MAX_DAI_REQUEST = 'GET_MAX_DAI_REQUEST';
export const GET_MAX_DAI_SUCCESS = 'GET_MAX_DAI_SUCCESS';
export const GET_MAX_DAI_FAILURE = 'GET_MAX_DAI_FAILURE';

export const REPAY_DAI_REQUEST = 'REPAY_DAI_REQUEST';
export const REPAY_DAI_SUCCESS = 'REPAY_DAI_SUCCESS';
export const REPAY_DAI_FAILURE = 'REPAY_DAI_FAILURE';

export const WITHDRAW_ETH_REQUEST = 'WITHDRAW_ETH_REQUEST';
export const WITHDRAW_ETH_SUCCESS = 'WITHDRAW_ETH_SUCCESS';
export const WITHDRAW_ETH_FAILURE = 'WITHDRAW_ETH_FAILURE';

export const GET_MAX_ETH_WITHDRAW_REQUEST = 'GET_MAX_ETH_WITHDRAW_REQUEST';
export const GET_MAX_ETH_WITHDRAW_SUCCESS = 'GET_MAX_ETH_WITHDRAW_SUCCESS';
export const GET_MAX_ETH_WITHDRAW_FAILURE = 'GET_MAX_ETH_WITHDRAW_FAILURE';

export const ADD_COLLATERAL_REQUEST = 'ADD_COLLATERAL_REQUEST';
export const ADD_COLLATERAL_SUCCESS = 'ADD_COLLATERAL_SUCCESS';
export const ADD_COLLATERAL_FAILURE = 'ADD_COLLATERAL_FAILURE';

export const GET_AFTER_CDP_REQUEST = 'GET_AFTER_CDP_REQUEST';
export const GET_AFTER_CDP_SUCCESS = 'GET_AFTER_CDP_SUCCESS';
export const GET_AFTER_CDP_FAILURE = 'GET_AFTER_CDP_FAILURE';

export const APPROVE_DAI_REQUEST = 'APPROVE_DAI_REQUEST';
export const APPROVE_DAI_SUCCESS = 'APPROVE_DAI_SUCCESS';
export const APPROVE_DAI_FAILURE = 'APPROVE_DAI_FAILURE';

export const APPROVE_MAKER_REQUEST = 'APPROVE_MAKER_REQUEST';
export const APPROVE_MAKER_SUCCESS = 'APPROVE_MAKER_SUCCESS';
export const APPROVE_MAKER_FAILURE = 'APPROVE_MAKER_FAILURE';

export const TRANSFER_CDP_REQUEST = 'TRANSFER_CDP_REQUEST';
export const TRANSFER_CDP_SUCCESS = 'TRANSFER_CDP_SUCCESS';
export const TRANSFER_CDP_FAILURE = 'TRANSFER_CDP_FAILURE';

export const PAYBACK_DAI_REQUEST = 'PAYBACK_DAI_REQUEST';
export const PAYBACK_DAI_SUCCESS = 'PAYBACK_DAI_SUCCESS';
export const PAYBACK_DAI_FAILURE = 'PAYBACK_DAI_FAILURE';

export const GET_REPAY_MODAL_DATA_REQUEST = 'GET_REPAY_MODAL_DATA_REQUEST';
export const GET_REPAY_MODAL_DATA_SUCCESS = 'GET_REPAY_MODAL_DATA_SUCCESS';
export const GET_REPAY_MODAL_DATA_FAILURE = 'GET_REPAY_MODAL_DATA_FAILURE';
export const RESET_REPAY_MODAL = 'RESET_REPAY_MODAL';

export const BOOST_REQUEST = 'BOOST_REQUEST';
export const BOOST_SUCCESS = 'BOOST_SUCCESS';
export const BOOST_FAILURE = 'BOOST_FAILURE';

export const GET_BOOST_MODAL_DATA_REQUEST = 'GET_BOOST_MODAL_DATA_REQUEST';
export const GET_BOOST_MODAL_DATA_SUCCESS = 'GET_BOOST_MODAL_DATA_SUCCESS';
export const GET_BOOST_MODAL_DATA_FAILURE = 'GET_BOOST_MODAL_DATA_FAILURE';
export const RESET_BOOST_MODAL = 'RESET_BOOST_MODAL';

export const GET_MAX_ETH_REPAY_REQUEST = 'GET_MAX_ETH_REPAY_REQUEST';
export const GET_MAX_ETH_REPAY_SUCCESS = 'GET_MAX_ETH_REPAY_SUCCESS';
export const GET_MAX_ETH_REPAY_FAILURE = 'GET_MAX_ETH_REPAY_FAILURE';

export const GET_MAX_DAI_BOOST_REQUEST = 'GET_MAX_DAI_BOOST_REQUEST';
export const GET_MAX_DAI_BOOST_SUCCESS = 'GET_MAX_DAI_BOOST_SUCCESS';
export const GET_MAX_DAI_BOOST_FAILURE = 'GET_MAX_DAI_BOOST_FAILURE';
