export const CONNECT_PROVIDER = 'CONNECT_PROVIDER';
export const CONNECT_PROVIDER_SUCCESS = 'CONNECT_PROVIDER_SUCCESS';
export const CONNECT_PROVIDER_FAILURE = 'CONNECT_PROVIDER_FAILURE';

export const GET_CDP_REQUEST = 'GET_CDP_REQUEST';
export const GET_CDP_SUCCESS = 'GET_CDP_SUCCESS';
export const GET_CDP_FAILURE = 'GET_CDP_FAILURE';

export const GET_CDPS_SUCCESS = 'GET_CDPS_SUCCESS';

export const SWITCH_CDP = 'SWITCH_CDP';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_FINISHED = 'LOGIN_FINISHED';

export const GET_ETH_PRICE_REQUEST = 'GET_ETH_PRICE_REQUEST';
export const GET_ETH_PRICE_SUCCESS = 'GET_ETH_PRICE_SUCCESS';

export const ADD_PROXY_ADDRESS = 'ADD_PROXY_ADDRESS';

export const GET_CLOSE_DATA_REQUEST = 'GET_CLOSE_DATA_REQUEST';
export const GET_CLOSE_DATA_SUCCESS = 'GET_CLOSE_DATA_SUCCESS';
export const GET_CLOSE_DATA_FAILURE = 'GET_CLOSE_DATA_FAILURE';

export const SUBSCRIBE_COMING_SOON_REQUEST = 'SUBSCRIBE_COMING_SOON_REQUEST';
export const SUBSCRIBE_COMING_SOON_SUCCESS = 'SUBSCRIBE_COMING_SOON_SUCCESS';
export const SUBSCRIBE_COMING_SOON_FAILURE = 'SUBSCRIBE_COMING_SOON_FAILURE';
export const RESET_SUBSCRIBE_COMING_SOON = 'RESET_SUBSCRIBE_COMING_SOON';

export const CDP_IN_CDPS_CHANGED = 'CDP_IN_CDPS_CHANGED';

export const SUBMIT_CONTACT_US_REQUEST = 'SUBMIT_CONTACT_US_REQUEST';
export const SUBMIT_CONTACT_US_SUCCESS = 'SUBMIT_CONTACT_US_SUCCESS';
export const SUBMIT_CONTACT_US_FAILURE = 'SUBMIT_CONTACT_US_FAILURE';
export const RESET_CONTACT_US = 'RESET_CONTACT_US';

export const CHANGE_LEDGER_ACC_TYPE = 'CHANGE_LEDGER_ACC_TYPE';

export const LIST_LEDGER_ACCOUNTS_REQUEST = 'LIST_LEDGER_ACCOUNTS_REQUEST';
export const LIST_LEDGER_ACCOUNTS_SUCCESS = 'LIST_LEDGER_ACCOUNTS_SUCCESS';
export const LIST_LEDGER_ACCOUNTS_FAILURE = 'LIST_LEDGER_ACCOUNTS_FAILURE';

export const SET_LEDGER_PATH = 'SET_LEDGER_PATH';
