export const CONNECT_PROVIDER = 'CONNECT_PROVIDER';
export const CONNECT_PROVIDER_SUCCESS = 'CONNECT_PROVIDER_SUCCESS';
export const CONNECT_PROVIDER_FAILURE = 'CONNECT_PROVIDER_FAILURE';

export const GET_CDP_REQUEST = 'GET_CDP_REQUEST';
export const GET_CDP_SUCCESS = 'GET_CDP_SUCCESS';
export const GET_CDP_FAILURE = 'GET_CDP_FAILURE';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_FINISHED = 'LOGIN_FINISHED';

export const GET_ETH_PRICE_REQUEST = 'GET_ETH_PRICE_REQUEST';
export const GET_ETH_PRICE_SUCCESS = 'GET_ETH_PRICE_SUCCESS';

export const ADD_PROXY_ADDRESS = 'ADD_PROXY_ADDRESS';
