export const CONNECT_PROVIDER = 'CONNECT_PROVIDER';
export const CONNECT_PROVIDER_SUCCESS = 'CONNECT_PROVIDER_SUCCESS';
export const CONNECT_PROVIDER_FAILURE = 'CONNECT_PROVIDER_FAILURE';

export const GET_CDP_REQUEST = 'GET_CDP_REQUEST';
export const GET_CDP_SUCCESS = 'GET_CDP_SUCCESS';
export const GET_CDP_FAILURE = 'GET_CDP_FAILURE';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_FINISHED = 'LOGIN_FINISHED';

export const GET_ETH_PRICE_REQUEST = 'GET_ETH_PRICE_REQUEST';
export const GET_ETH_PRICE_SUCCESS = 'GET_ETH_PRICE_SUCCESS';

export const ADD_PROXY_ADDRESS = 'ADD_PROXY_ADDRESS';

export const GET_CLOSE_DATA_REQUEST = 'GET_CLOSE_DATA_REQUEST';
export const GET_CLOSE_DATA_SUCCESS = 'GET_CLOSE_DATA_SUCCESS';
export const GET_CLOSE_DATA_FAILURE = 'GET_CLOSE_DATA_FAILURE';

export const SUBSCRIBE_COMING_SOON_REQUEST = 'SUBSCRIBE_COMING_SOON_REQUEST';
export const SUBSCRIBE_COMING_SOON_SUCCESS = 'SUBSCRIBE_COMING_SOON_SUCCESS';
export const SUBSCRIBE_COMING_SOON_FAILURE = 'SUBSCRIBE_COMING_SOON_FAILURE';
export const RESET_SUBSCRIBE_COMING_SOON = 'RESET_SUBSCRIBE_COMING_SOON';
