export const GET_MARKETPLACE_CDP_DATA_REQUEST = 'GET_MARKETPLACE_CDP_DATA_REQUEST';
export const GET_MARKETPLACE_CDP_DATA_SUCCESS = 'GET_MARKETPLACE_CDP_DATA_SUCCESS';
export const GET_MARKETPLACE_CDP_DATA_FAILURE = 'GET_MARKETPLACE_CDP_DATA_FAILURE';

export const SELL_CDP_REQUEST = 'SELL_CDP_REQUEST';
export const SELL_CDP_SUCCESS = 'SELL_CDP_SUCCESS';
export const SELL_CDP_FAILURE = 'SELL_CDP_FAILURE';
export const RESET_SELL_CDP_FORM = 'RESET_SELL_CDP_FORM';

export const BUY_CDP_REQUEST = 'BUY_CDP_REQUEST';
export const BUY_CDP_SUCCESS = 'BUY_CDP_SUCCESS';
export const BUY_CDP_FAILURE = 'BUY_CDP_FAILURE';

export const CANCEL_SELL_CDP_REQUEST = 'CANCEL_SELL_CDP_REQUEST';
export const CANCEL_SELL_CDP_SUCCESS = 'CANCEL_SELL_CDP_SUCCESS';
export const CANCEL_SELL_CDP_FAILURE = 'CANCEL_SELL_CDP_FAILURE';
export const RESET_CANCEL_SELL_CDP = 'RESET_CANCEL_SELL_CDP';
