export const GET_MARKETPLACE_CDP_DATA_REQUEST = 'GET_MARKETPLACE_CDP_DATA_REQUEST';
export const GET_MARKETPLACE_CDP_DATA_SUCCESS = 'GET_MARKETPLACE_CDP_DATA_SUCCESS';
export const GET_MARKETPLACE_CDP_DATA_FAILURE = 'GET_MARKETPLACE_CDP_DATA_FAILURE';
