export const MIGRATE_CDP_REQUEST = 'MIGRATE_CDP_REQUEST';
export const MIGRATE_CDP_SUCCESS = 'MIGRATE_CDP_SUCCESS';
export const MIGRATE_CDP_FAILURE = 'MIGRATE_CDP_FAILURE';
export const MIGRATE_CDP_RESET = 'MIGRATE_CDP_RESET';
