export const RESET_ONBOARDING_WIZARD = 'RESET_ONBOARDING_WIZARD';
export const CREATE_CDP_REQUEST = 'CREATE_CDP_REQUEST';

export const CREATE_CDP_SUCCESS = 'CREATE_CDP_SUCCESS';
export const CREATE_CDP_ERROR = 'CREATE_CDP_ERROR';
export const MONITORING_SUBSCRIBE_REQUEST = 'MONITORING_SUBSCRIBE_REQUEST';

export const MONITORING_SUBSCRIBE_SUCCESS = 'MONITORING_SUBSCRIBE_SUCCESS';
export const MONITORING_SUBSCRIBE_FAILURE = 'MONITORING_SUBSCRIBE_FAILURE';

export const SET_ONBOARDING_FINISHED = 'SET_ONBOARDING_FINISHED';

export const SET_CREATE_CDP_CALC_VALUES = 'SET_CREATE_CDP_CALC_VALUES';

export const ADD_CDP_TO_CDPS = 'ADD_CDP_TO_CDPS';

export const RESET_CREATE_CDP_FORM = 'RESET_CREATE_CDP_FORM';
