export const RESET_ONBOARDING_WIZARD = 'RESET_ONBOARDING_WIZARD';

export const CREATE_CDP_REQUEST = 'CREATE_CDP_REQUEST';
export const CREATE_CDP_SUCCESS = 'CREATE_CDP_SUCCESS';
export const CREATE_CDP_ERROR = 'CREATE_CDP_ERROR';
